### PR TITLE
Fix/issue 183 non openai hallucination check

### PR DESCRIPTION
**Pull request by Pouyanpi**
Allow the use of non OpenAI llm models.

### CODE REVIEW

**Comment by Pouyanpi** [comment]
@drazvan, is it Ok to delegate the check for "temperature" or "n" to the "LLMParams" like this?

**Review by drazvan — CHANGES_REQUESTED** [review]
@pouyanpi: we should do a proactive check if the LLM supports the `n` parameter, similar to https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/rails/llm/llmrails.py#L371. Otherwise, this will most likely raise an error.

**Comment by Pouyanpi** [comment]
@drazvan, I made the change, please have a look.

**Review by drazvan — APPROVED** [review]
Thanks :+1:.

**Pull request merged**
