### PR TITLE
azure is supported

### PR DESCRIPTION
**Pull request by smartestrobotdai**
Azure support is added.
In config.xml, you could configure 'azure' as provider, like:
models:
  - type: main
    engine: azure
    model: gpt-4-1106-preview
    parameters:
      azure_endpoint: <the end point of the deployment>
      api_version: 2023-07-01-preview
      deployment_name: <your deployment name>
      api_key: <your azure key>

### CODE REVIEW

**Comment by drazvan** [comment]
Thanks @smartestrobotdai ! I see that one of the commits is not signed. Can you maybe squash the two and force-push the branch? (and the new commit should be signed automatically).

**Comment by smartestrobotdai** [comment]
@drazvan Thanks!  I squashed the commits and forcely pushed, please check if it is good now.

**Review by drazvan — APPROVED** [review]
Looks good 👍 . Thanks!

**Comment by onkarrajambatwar** [comment]
@drazvan Could you please add exampl related to Azure LLM, may be sample config.

**Comment by trebedea** [comment]
> @drazvan Could you please add exampl related to Azure LLM, may be sample config. Also, in which version I can see this change?

@onkarrajambatwar , doesn't this work for you: https://github.com/NVIDIA/NeMo-Guardrails/discussions/249

**Pull request merged**
