### PR TITLE
fix(library): Update Cleanlab's return type

### PR DESCRIPTION
**Pull request by AshishSardana**
Cleanlab's latest release (v2.5 on 09/20) to `cleanlab-studio` pypi package updates the return type of `get_trustworthiness_score_async()` method from `float` to `typeddict`. Therefore, the `trustworthiness_score` is indexed out from the typed dict.

The fix is verified after updating `pip install -U cleanlab-studio`.

### CODE REVIEW

**Comment by AshishSardana** [comment]
Hi @Pouyanpi , can you give this a quick look?

**Review by Pouyanpi — APPROVED** [review]
LGTM @AshishSardana, Thanks for the PR!

You just need to [sign your commits](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/CONTRIBUTING.md#submitting-your-work) then we can merge.

**Comment by AshishSardana** [comment]
I did sign the commit on this PR, manually. I've been using the same signing technique for older commits/PRs.

Screenshot 2024-10-15 at 01 22 08

**Comment by Pouyanpi** [comment]
@AshishSardana, I can see that your commit is not gpg signed, you can also verify that by 

```bash
git log --show-signature
```

You can see how it differs from its prev commits.

Please also rebase your branch onto the latest develop branch as some tests are failing due to the latest changes of the repo.

**Comment by AshishSardana** [comment]
@Pouyanpi thank you for our suggestions! i've setup GPG, signed my commits and rebased my branch onto latest develop.

**Comment by AshishSardana** [comment]
@Pouyanpi all the checks pass & the PR is ready to be merged.

**Pull request merged**
