### PR TITLE
fix utf-8 encoding issue, add embedding_model configuration

### PR DESCRIPTION
**Pull request by yuekaizhang**
1. fix 'utf-8' encoding issue for *.co and *.yml: to better support examples using prompts with different languages
2. configure embedding model through config.yaml, such that we could use multilingual embedding model

### CODE REVIEW

**Comment by drazvan** [comment]
Thanks for this @yuekaizhang! Looks good 👍 . Could you please sign the commit and force-push the branch again? (https://github.com/NVIDIA/NeMo-Guardrails/blob/main/CONTRIBUTING.md#signing-your-work). If you're able to do this in the next few hours, we can merge it as part of the `0.3.0` release, which is today. 

The only thing missing is a mention in the documentation in the Configuration Guide, but I'm happy to add that myself.

**Comment by yuekaizhang** [comment]
> Thanks for this @yuekaizhang! Looks good 👍 . Could you please sign the commit and force-push the branch again? (https://github.com/NVIDIA/NeMo-Guardrails/blob/main/CONTRIBUTING.md#signing-your-work). If you're able to do this in the next few hours, we can merge it as part of the `0.3.0` release, which is today.
> 
> The only thing missing is a mention in the documentation in the Configuration Guide, but I'm happy to add that myself.

I am happy to finish that now. However, I have already tried git commit -s -m "". I was wondering how to fix.

**Comment by yuekaizhang** [comment]
image

**Comment by drazvan** [comment]
You can checkout this guide from GitLab: https://docs.gitlab.com/ee/user/project/repository/gpg_signed_commits/. And make sure you add the generated GPG key to your GitHub account. To resign the commit, since there's only one, the easiest way is to make it again i.e. `git reset HEAD~1` and the `git commit -m "..."`. Make sure you run `git config --global commit.gpgsign true` beforehand so that all commits get signed automatically.

**Comment by yuekaizhang** [comment]
> You can checkout this guide from GitLab: https://docs.gitlab.com/ee/user/project/repository/gpg_signed_commits/. And make sure you add the generated GPG key to your GitHub account. To resign the commit, since there's only one, the easiest way is to make it again i.e. `git reset HEAD~1` and the `git commit -m "..."`. Make sure you run `git config --global commit.gpgsign true` beforehand so that all commits get signed automatically.

Many thanks. Done.

**Pull request merged**
