### PR TITLE
Add Colang commenting feature to VScode extension

### PR DESCRIPTION
**Pull request by radinshayanfar**
This PR adds Colang commenting feature to VSCode extension. By pressing `Ctrl + /`, VSCode can automatically comment out a line or the selected block.

### CODE REVIEW

**Comment by drazvan** [comment]
Thanks, @radinshayanfar. If you can fix the formatting issue (see the failed tests), we can merge. You should install pre-commit and run `pre-commit run --all-files`.

**Comment by radinshayanfar** [comment]
Hi @drazvan - Thank you for your time. I fixed the formatting issue and it now passes the pre-commit hooks.

**Comment by Pouyanpi** [comment]
@radinshayanfar Thanks for your PR!

Due to recent changes in the repo, the tests are failing. Rebasing your branch onto the latest `develop` branch might resolve the issue. Please try doing a rebase and we do the merge once the pipeline goes green.

**Comment by radinshayanfar** [comment]
Hi @Pouyanpi - I merged the branch with develop and it seems to be passing all the tests on my system.

**Review by Pouyanpi — APPROVED** [review]
Looks good, thanks!

**Comment by radinshayanfar** [comment]
@Pouyanpi @drazvan 
Thank you for approving this. Can this be merged?

**Pull request merged**
