### PR TITLE
fix: move relevant chunks before current conversations

### PR DESCRIPTION
**Pull request by Pouyanpi**
Otherwise the bot will generate based on the relevant chunks only.

### CODE REVIEW

**Comment by Pouyanpi** [comment]
@drazvan would you have a look? Please try out abc_v2 on develop branch to see the issue. Can it be included in the patch release?

**Comment by schuellc-nvidia** [comment]
I think we need to better test the introduced change in #745.
Changing the prompts like that can result in unexpected behavior. E.g. I would suggest removing the markdown notation. Also, we need to take a look at the prompt templates for the GPT 4 and Llama 3 models.

**Comment by Pouyanpi** [comment]
@schuellc-nvidia, are we good to merge this PR considering #809 ?

**Review by schuellc-nvidia — APPROVED** [review]
All good for me

**Pull request merged**
