### PR TITLE
Update  codebase with appropriate coding standards

### PR DESCRIPTION
**Pull request by rajveer43**
@drazvan now here the commit  is verified. I will update all the docstrings soon in this branch.

### CODE REVIEW

**Comment by rajveer43** [comment]
@drazvan you can review this and let me know if any fix is required.

**Review by drazvan — APPROVED** [review]
Thanks again for taking the time to do this @rajveer43! 👍

**Comment by rajveer43** [comment]
> Thanks again for taking the time to do this @rajveer43! 👍

there are still some left will do that in another PR!

**Comment by drazvan** [comment]
Yes. Soon, we should add a linter as part of the CI to check the proper formatting of all docstrings (among other things).

**Pull request merged**
