### PR TITLE
Add support for Falcon

### PR DESCRIPTION
**Pull request by mohiitaa**
This PR adds support for Falcon-40B, Falcon-40B-instruct, Falcon-7B, and Falcon-7B-instruct models. The default is set to Falcon-7B-instruct. I need some help running the Topical Rails Evaluation on these models. Would appreciate any help, thanks!

### CODE REVIEW

**Comment by drazvan** [comment]
Thanks for this @mohiitaa! We can do the evaluation in a separate PR. @trebedea can help with that.
As per our contribution guidelines, your commits need to be signed. Refer to this on how to configure your signature: 
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits .
You should rebase your branch and force-push. Once done, we can merge. Thanks again!

**Comment by mohiitaa** [comment]
> Thanks for this @mohiitaa! We can do the evaluation in a separate PR. @trebedea can help with that. As per our contribution guidelines, your commits need to be signed. Refer to this on how to configure your signature: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits . You should rebase your branch and force-push. Once done, we can merge. Thanks again!

Thanks @drazvan! Yes, I noticed I hadn't signed my commit so I made a new commit ([c2a633d](https://github.com/NVIDIA/NeMo-Guardrails/pull/117/commits/c2a633d1a14561adb469d569a407c48771fc2251)) and force-pushed it. Is this sufficient?

**Comment by mohiitaa** [comment]
I've just rebased it as well @drazvan! Thanks for your help.

**Comment by drazvan** [comment]
@mohiitaa : can you rebase this on top of the `develop` brach and update the MR to target that branch? Thanks!

**Comment by drazvan** [comment]
Closing as old with no recent activity.

**Pull request closed without merging**
