### PR TITLE
Update of documentation

### PR DESCRIPTION
**Pull request by rajveer43**
@drazvan 

here is the new PR as you requested [](https://github.com/NVIDIA/NeMo-Guardrails/pull/130#issuecomment-1828020288) here

### CODE REVIEW

**Comment by drazvan** [comment]
@rajveer43 : ping on updating this as per my comments in the issue. Thanks!

**Comment by drazvan** [comment]
@rajveer43 : let me know if you still want to contribute this. The code base continues to change, and more and more conflicts will stack up.

**Comment by rajveer43** [comment]
> @rajveer43 : let me know if you still want to contribute this. The code base continues to change, and more and more conflicts will stack up.

@drazvan, I want to contribute and I will update it as per your instructions

**Comment by drazvan** [comment]
Thanks for confirming! Let me know if you need help sorting the latest conflicts.

**Comment by rajveer43** [comment]
There was some issues with configuration I have sorted it

**Pull request closed without merging**
