### PR TITLE
Update of the documentation

### PR DESCRIPTION
**Pull request by rajveer43**

### CODE REVIEW

**Comment by drazvan** [comment]
Thanks a lot for this @rajveer43! I have not reviewed all the comments in detail, but looks good 👍 . It was on my TODO list to update them to the right format. This is hugely helpful!

Before we can merge, there's a couple of house-keeping things to fix:
1. Configure signed commits so that they show up as "Verified" (https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits). As per our Contributing guidelines, the all commits must be signed. 
2. Rebase the branch on the current main and force-push (this will actually apply the signature automatically to all the commits you've made). 

Once that's done, we can merge.

**Comment by drazvan** [comment]
@rajveer43 : can you rebase this on the `develop` branch and target that branch instead for the MR? Thanks!

**Comment by rajveer43** [comment]
> @rajveer43 : I would really like to merge this. Apologies it's taken so long to look at this. Happy to help with reviewing if there are conflicts, given there were many changes to the codebase in the last two months.

Sure, I will try  rebase this on the `develop` branch

**Comment by rajveer43** [comment]
as you can see 
image


my `patch-1` branch is already rebased on `develop` branch. if I try merging here , I fear my changes will be discarded also I have to sign all my previous commits can you provide steps to avoid loss of work

**Comment by drazvan** [comment]
@rajveer43 : The easiest way was to squash everything when solving the conflicts. I've pushed a single commit here: https://github.com/NVIDIA/NeMo-Guardrails/tree/feature/docstring-updates. 
Here are the steps for you:
1. Clone that branch locally.
2. Do a `git reset HEAD~1` (which drops my commit, but keeps the changes locally)
3. Do a `git commit -a -S -m "Updating docstrings."`
4. Push the branch in your fork and create a new PR against it. 

Thanks again for all the effort!

**Comment by drazvan** [comment]
@rajveer43 : I think you've still used the previous branch, and I'm still seeing multiple commits in the PR

image

If you follow the exact instructions I've provided above, it should result in a single commit PR, which should also be properly signed. Can you try that approach instead?

Thanks!

**Comment by drazvan** [comment]
Closing as duplicate of #199 .

**Pull request closed without merging**
